### ISSUE TITLE
Planned issues to tackle

### ISSUE THREAD

**Issue by CyborgGecko** [Multi-Branch-Drifting-2410/libgdx#1]
Reproducable: Grayscale png not properly loaded #4029 https://github.com/libgdx/libgdx/issues/4029

Fix broken things due to changes to Graphics#getWidth() #3702 https://github.com/libgdx/libgdx/issues/3702

Support for complex font rendering (Chinese, Arabic, ...) #1589 https://github.com/libgdx/libgdx/issues/1589

No option for rendering Arc Lines #4313 https://github.com/libgdx/libgdx/issues/4313

ButtonGroup throws ClassCastException when accessing through getAllChecked() #4294
https://github.com/libgdx/libgdx/issues/4294

**Comment by iibrahimbakr** [comment]
RTL languages like Arabic not just direction from RIGHT to LEFT, but how connect their letters with each other and some letters as a block with 2 or more letters.
So, I do it with fully supporting RTL language. 
https://github.com/CrowniAPIs/libGDX-RTL-Language
