### ISSUE TITLE
Fix broken things due to changes to Graphics#getWidth() 

### ISSUE THREAD

**Issue by CyborgGecko** [Multi-Branch-Drifting-2410/libgdx#3]
Fix broken things due to changes to Graphics#getWidth() #3702 https://github.com/libgdx/libgdx/issues/3702

**Comment by jlnguy** [comment]
Considering removing this bug; the classes still affected by _**gdx.graphics.getWidth()**_ are _ResolutionFileResolver.java_ and _ParticleShader.java_. In the case of ParticleShader, it has an alternate class that is used instead; for ResolutionFileResolver, there is a backup case in the folder where the file is stored anyway.

**Comment by aalnuaimi** [comment]
The issue was in ResolutionFileResolver.java , Basiclly we have to deactivate Resolution bestResolution and we used the (fileName) as baseResolver .

**Comment by jlnguy** [comment]
Fix was the second getWidth() issue; 

https://github.com/libgdx/libgdx/blob/fde893cec5448fdd09e778d1c103aac474950873/gdx/src/com/badlogic/gdx/assets/loaders/resolvers/ResolutionFileResolver.java#L103
