### ISSUE TITLE
Support for complex font rendering (Chinese, Arabic, ...)

### ISSUE THREAD

**Issue by CyborgGecko** [Multi-Branch-Drifting-2410/libgdx#4]
Support for complex font rendering (Chinese, Arabic, ...) #1589 https://github.com/libgdx/libgdx/issues/1589

**Comment by jlnguy** [comment]
Possibly too difficult for us to do.

**Comment by fsavino** [comment]
Issue was closed in main LibGDX repository as another function exists which performs the proposed enhancement.

**Comment by iibrahimbakr** [comment]
RTL languages like Arabic not just direction from RIGHT to LEFT, but how connect their letters with each other and some letters as a block with 2 or more letters.
So, I do it with fully supporting RTL language. 
https://github.com/CrowniAPIs/libGDX-RTL-Language
