### ISSUE TITLE
ButtonGroup throws ClassCastException when accessing through getAllChecked()

### ISSUE THREAD

**Issue by CyborgGecko** [Multi-Branch-Drifting-2410/libgdx#6]
ButtonGroup throws ClassCastException when accessing through getAllChecked() #4294
https://github.com/libgdx/libgdx/issues/4294

**Comment by CyborgGecko** [comment]
Bug is hard to reproduce. Possibly user error? Will investigate further.

**Comment by CyborgGecko** [comment]
I will see if I can get the poster to provide a file that causes the bug.

**Comment by jlnguy** [comment]
From Casey: make a toString method in the ButtonGroup Class thing.
