### ISSUE TITLE
Box2D Chain Shape, isLooped doesnt stick. #3554

### ISSUE THREAD

**Issue by jlnguy** [Multi-Branch-Drifting-2410/libgdx#7]
https://github.com/libgdx/libgdx/issues/3554
#### Issue details

The underlying c implementations doesn't have isLooped in the chain which causes the flag to get lost on retrieval of the shape from the fixture. I believe that checking for indentical first and last vertex in ChainShape#ChainShape(long) constructor would be a reasonable fix.

This prints good, than broken.

**Comment by CyborgGecko** [comment]
https://github.com/libgdx/libgdx/issues/3892

**Comment by jlnguy** [comment]
Unless you're saving the array used for the coordinates of the chain, then the flags should be set. Simply calling the class ChainShape.java and then creating a loop using createloop(Vector2[] vertices) will set the flag to true.

Technically I'm not seeing anything odd going on in this class, aside from using the same variable name to create a secondary loop and causing a crash (Could have just been me messing up.)

**Comment by jlnguy** [comment]
Update: Putting the code given by the issue poster into _Box2DTest.java_ and the error is reproducible. The Lines of code that affect this issue is assumed to be located at line 41 in _ChainShape.java_ (Located in the folder **gdx-box2d**)

Will upload my version of _Box2DTest.java_ on Friday.

Result screen:

> About: Florida Institute of Technology,
> Intro to Software Engineering - CSE2410 - Fall 2016
> Andrew Greco, Jessica Nguy, Frank Savino, Ahmed Alnuaimi
> 
> New shape looks good
> Fixture shape looks broken

**Comment by jlnguy** [comment]
Box2D has a lot of unused code that's been put into comments and left to sit there. 
- Actually, most of the commented out code refers to JNI (Java Native Interface) language
- JNI links to .cpp and .h files in the jni folder.

The bug creator used createLoop(float[]), which leads to a class declaration and commented-out (JNI) code. This is why the float[] loop isn't drawn in the Test. 

There is a JNI folder located in each class. The Java file points to the header(?) file that points to the .cpp file, which then does stuff in C++ and returns stuff.

**Comment by jlnguy** [comment]
The guy calls fixture.getShape(). The getShape() method gets the memory of the item being passed through, then re-writes a new declaration of an object _on top of_ the existing memory address. So getShape() re-writes the object with a new declaration. The boolean value stored in the original chainShape object is lost.

To combat this, change **boolean isLooped = false** to **static boolean isLooped = false** in _ChainShape.java_. Add a method at the bottom of _ChainShape.java_:

`public static void setLooped() {
                isLooped = true;
        }
` 

In _Fixture.java_'s getShape(), add a method **ChainShape.setLooped()** in case 0 and case 2. This is a quick fix for the guy's error.

Cons: Questionable; dirty; and changes stuff in a getter method. Further testing needs to be done to see if changing **isLooped** to static affects the rest of the code. Also need to test how to implement the boolean change in case 3.

**Workspace:** Box2DTest.java, ChainShape.java, Shape.java, Fixture.java, Body.java

**Comment by jlnguy** [comment]
Hi. Committed my fixes to the main branch.

**Comment by jlnguy** [comment]
Closing because we r done!
